---
# tasks file for ./roles/create_dirs

- name: Install Dependencies
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - libapr1
    - libapr1-dev
    - libaprutil1-dev 
    - autoconf
    - automake
    - build-essential
    - ca-certificates
    - cmake
    - curl
    - git
    - libpcre3
    - libpcre3-dev
    - libssl-dev
    - libtool
    - libxml2-dev
    - libxslt1-dev
    - lsb-release
    - tar
    - uuid-dev
    - unzip
    - wget
    - zlib1g-dev
    
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Create dirs for Nginx
  import_tasks: nginx.yml
  
- name: Create dirs for Apache
  import_tasks: apache.yml
