---
# vars file for ./roles/install

nginx_version: nginx-1.21.1
apache_version: httpd-2.4.53
mysql_version: mysql-5.6.44-linux-glibc2.12-x86_64

nginx_tarball_url: "http://nginx.org/download/{{ nginx_version }}.tar.gz"
apache_tarball_url: "https://dlcdn.apache.org/httpd/{{ apache_version }}.tar.gz"
mysql_tarball_url: "https://downloads.mysql.com/archives/get/p/23/file/{{ mysql_version }}.tar.gz"

nginx_install_dir: "/usr/local/src/nginx/"
apache_install_dir: "/usr/local/src/apache/"
mysql_install_dir: "/usr/local/src/mysql/"

nginx_custom_modules: "--with-http_sub_module --with-http_realip_module --with-http_stub_status_module --with-http_slice_module --with-http_auth_request_module --with-http_mp4_module --with-http_v2_module --with-http_ssl_module --with-file-aio"
apache_custom_modules: "--enable-module=rewrite --enable-shared=rewrite --enable-module=proxy --enable-shared=proxy --with-mpm=event"
mysql_custom_modules: ""

nginx_custom_config: "--prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --user=nginx --group=nginx --with-cc-opt=-Wno-deprecated-declarations --with-cc-opt=-Wno-ignored-qualifiers"
apache_custom_config: "--prefix=/usr/local/apache"
mysql_custom_config: "--prefix=/usr/local/apache"

nginx_conf_url: "https://raw.githubusercontent.com/RukInDaHouse/configs/f32ef395a0e70759f44f7ddb98ace22367b51210/nginx/nginx.conf"
apache_conf_url: "https://raw.githubusercontent.com/RukInDaHouse/configs/develop/apache2/httpd.conf"
mysql_conf_url: "https://raw.githubusercontent.com/RukInDaHouse/configs/develop/mysql/my.conf"

nginx_service_url: "https://raw.githubusercontent.com/RukInDaHouse/configs/f32ef395a0e70759f44f7ddb98ace22367b51210/nginx/nginx.service"
apache_service_url: "https://raw.githubusercontent.com/RukInDaHouse/configs/develop/apache2/httpd.service"
mysql_service_url: "https://raw.githubusercontent.com/RukInDaHouse/configs/develop/mysql/mysql.service"

