- name: Creating NGINX conf file
  become: yes
  template:
    src: intsall.sh
    dest: "install.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0655

- name: Configuring NGINX source
  command: "./install.sh"
  register: nginx_configu
