---
# tasks file for ./roles/install (MySql)

- name: Download Boost
  get_url:
    url: "{{ boost_tarball_url }}"
    dest: "{{ mysql_install_dir }}{{ boost_version }}.tar.gz"
  
- name: Unpack Boost
  unarchive:
    copy: no
    dest: "{{ mysql_install_dir }}{{ boost_version }}"
    src: "{{ mysql_install_dir }}{{ boost_version }}.tar.gz"
  when: nginx_source.changed
  
- name: Download MySql sources
  get_url:
    url: "{{ mysql_tarball_url }}"
    dest: "{{ nginx_install_dir }}{{ mysql_version }}.tar.gz"

- name: Unpack Mysql
  unarchive:
    copy: no
    dest: "{{ nginx_install_dir }}"
    src: "{{ nginx_install_dir }}{{ mysql_version }}.tar.gz"

- name: Configure Mysql install with Cmake
  command: "cmake .. -DWITH_BOOST={{ mysql_install_dir }}{{ boost_version }}"
  args:
    chdir: "{{ mysql_install_dir }}{{ mysql_version }}/bld"

- name: Make Mysql
  command: "make"
  args:
    chdir: "{{ mysql_install_dir }}{{ mysql_version }}/bld"
  
- name: Install Mysql
  command: "make install"
  args:
    chdir: "{{ mysql_install_dir }}{{ mysql_version }}/bld"

- name: Configure Mysql source (Part 1)
  command: "bin/mysqld --initialize --user=mysql"
  args:
    chdir: "/usr/local/mysql"
  
- name: Configure Mysql source (Part 2)
  command: "bin/mysql_ssl_rsa_setup"
  args:
    chdir: "/usr/local/mysql"
    
- name: Configure Mysql source (Part 3)
  command: "bin/mysqld_safe --user=mysql &"
  args:
    chdir: "/usr/local/mysql"
 
