---
# tasks file for ./roles/install (MySql)

- name: Download Boost
  get_url:
    url: "https://boostorg.jfrog.io/artifactory/main/release/1.73.0/source/boost_1_73_0.tar.gz"
    dest: "{{ mysql_install_dir }}.tar.gz"
  
- name: Unpack Boost
  unarchive:
    copy: no
    dest: "{{ mysql_install_dir }}boost_1_73_0"
    src: "{{ mysql_install_dir }}boost_1_73_0.tar.gz"
  when: nginx_source.changed
  
- name: Download MySql sources
  get_url:
    url: "https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-boost-8.0.28.tar.gz"
    dest: "{{ nginx_install_dir }}{{ nginx_version }}.tar.gz"

- name: Unpack Mysql
  unarchive:
    copy: no
    dest: "{{ nginx_install_dir }}"
    src: "{{ nginx_install_dir }}mysql-boost-8.0.28.tar.gz.tar.gz"

- name: Configure Mysql source
  command: "cmake .. -DWITH_BOOST={{ mysql_install_dir }}boost_1_73_0"
  args:
    chdir: "{{ mysql_install_dir }}mysql-8.0.28/bld"
  register: mysql_conf1
  
- name: Configure Mysql source
  command: "make"
  args:
    chdir: "{{ mysql_install_dir }}mysql-8.0.28/bld"
  register: mysql_conf1
  
- name: Configure Mysql source
  command: "make install"
  args:
    chdir: "{{ mysql_install_dir }}mysql-8.0.28/bld"
  register: mysql_conf1
  
- name: Create required Nginx dirs
  become: yes
  file:
    path: "/usr/local/mysql/mysql-files"
    state: directory
    owner: root
    mode: 0755  

- name: Configure Mysql source
  command: "bin/mysqld --initialize --user=mysql"
  args:
    chdir: "/usr/local/mysql"

  
- name: Configure Mysql source
  command: "bin/mysql_ssl_rsa_setup"
  args:
    chdir: "/usr/local/mysql"
    
- name: Configure Mysql source
  command: "bin/mysqld_safe --user=mysql &"
  args:
    chdir: "/usr/local/mysql"
 
